#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
from flask import Flask

pin_open = 17
pin_close = 18
pin_stop = 19

GPIO.setmode(GPIO.BCM)
GPIO.setup(pin_open, GPIO.OUT)
GPIO.setup(pin_close, GPIO.OUT)
GPIO.setup(pin_stop, GPIO.OUT)

app = Flask(__name__)

@app.route("/somfy/<state>")
def somfy(state):
    if state == "open":
	return set(pin_open)
    elif state == "close":
	return set(pin_close)
    elif state == "stop":
	return set(pin_stop)

def set(pin):
	GPIO.output(pin, True)
	time.sleep(0.5)
	GPIO.output(pin, False)
	return "ok"

if __name__ == "__main__":
    app.run(host="0.0.0.0")

