#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
from flask import Flask, redirect, url_for

pin_up = 17
pin_down = 18
pin_stop = 19

GPIO.setmode(GPIO.BCM)
GPIO.setup(pin_up, GPIO.OUT)
GPIO.setup(pin_down, GPIO.OUT)
GPIO.setup(pin_stop, GPIO.OUT)

app = Flask(__name__)

@app.route("/")
def index():
    redirect(url_for("static", filename="remote.html"))

@app.route("/somfy/<state>")
def somfy(state):
    if state == "up":
	return set(pin_up)
    elif state == "down":
	return set(pin_down)
    elif state == "stop":
	return set(pin_stop)

def set(pin):
	GPIO.output(pin, True)
	time.sleep(0.5)
	GPIO.output(pin, False)
	return "ok"

if __name__ == "__main__":
    app.run(host="0.0.0.0")

